# SPDX-FileCopyrightText: 2023 Alec Delaney, written for Adafruit Industries
#
# SPDX-License-Identifier: MIT

name: 🐞 Bug Report
description: Create a bug report to help us improve
labels:
  - bug
body:
  - type: markdown
    id: intro
    attributes:
      value: >-
        Thanks for using this library!  If you've encountered a bug,
        please use this form to submit a report to help us improve.
        Be sure to first check the [other issues](../issues) for this library to see if
        one already exists for your bug!
  - type: input
    id: library_version
    attributes:
      label: Library version
      description: >-
        You can find the library version by importing the library in
        [the REPL](https://learn.adafruit.com/welcome-to-circuitpython/the-repl)
        and using the `__version__` attribute.  For example,
        `import adafruit_bme680`, then `adafruit_bme680.__version__`.
      placeholder: 1.2.3
    validations:
      required: true
  - type: input
    id: firmware_version
    attributes:
      label: CircuitPython version
      description: >-
        The version of CircuitPython you're running. You can see it
        in the `boot_out.txt` file, as well as when you first enter
        the `REPL`.
      placeholder: |
        Adafruit CircuitPython 8.0.0 on 2023-02-10; Raspberry Pi Pico with rp2040
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: Code / REPL
      description: >-
        The code that is causing the issue.  This will automatically
        as Python when the form as submitted.
      placeholder: |
        import board
        import adafruit_bme680

        i2c = board.I2C()
        bme680 = adafruit_bme680.Adafruit_BME680_I2C(i2c, debug=True)
        while True:
            print("Pressure: %0.3f hPa" % bme680.pressure)
      render: python
    validations:
      required: true
  - type: textarea
    id: reproducible
    attributes:
      label: Minimum reproducible code
      description: >-
        The least amount of code needed to reproduce the issue
        - it may help us solve the problem faster.  This will render as
        Python when submitted.
      placeholder: |
        import board
        import adafruit_bme680
        i2c = board.I2C()
        bme680 = adafruit_bme680.Adafruit_BME680_I2C(i2c)
      render: python
  - type: textarea
    id: behavior
    attributes:
      label: Behavior
      description: >-
        Describe the behavior of the device as it relates to the bug, including
        any exceptions raised and hardware faults.  Use backticks for any code.
      placeholder: |
        ```shell
        Traceback (most recent call last):
          File "<stdin>", line 1, in <module>
          RuntimeError: Failed to find BME680!  Chip ID 0xA3
        ```
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Description / Additional information
      description: >-
        You can add any additional information that would be helpful here.
        For example, if your board has multiple revisions or specific hardware.
  - type: markdown
    id: coc
    attributes:
      value: >-
        Thanks for the report!  Note that we use the [Adafruit Community Code
        of Conduct](https://github.com/adafruit/Adafruit_Community_Code_of_Conduct/blob/main/code-of-conduct.md)
        along with community contributions like these to keep CircuitPython
        for everyone!
